#! /bin/sh

# this script parallelizes running the test.com script

p_e=`which parallel 2>&1`

if [ ! -x $p_e ] ; then
    echo "\

This script uses gnu parallel program avaiable at:
http://www.gnu.org/software/parallel
for ubuntu users: apt-get install parallel
                  it is a static executable: /usr/bin/parallel
                  ready to be coped elsewhere in the PATH...
"
    exit 0
fi


# where is the executable
# it can be specified as a first command line argument to the script
# default is OK if -p is specified as a configure argument

export chm_exec=${1:-../bin/charmm}

echo executable to be tested $chm_exec

## if [ $# -eq 0 ] ; then
if [ ! -x $chm_exec ] ; then
    echo different executable can be selected by specifying
    echo $0 "<path-to-charmm-executable>"
    exit 0
fi

# order here is: longer runs first!
tsts='41 37 40 39 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 38 42 43 44 45'

$p_e ./test.com keeps gnu output output_bench "{}" ::: $tsts

