MODULE CONSHELIX_FCM
  use chm_kinds
  use dimens_fcm
  use chm_types
  implicit none

#if KEY_CONSHELIX==1 /*CONSHELIX_FCM*/
  INTEGER,PARAMETER :: MXHEL=2,NCOOR=3,mxslt=100,MXCONSH=20

  real(chm_real) CAVEC(NCOOR,MXHEL),CBVEC(NCOOR,MXHEL), &
       CEVEC(NCOOR,MXHEL),CRVEC(NCOOR,MXHEL), &
       CPRVEC(NCOOR,MXSLT,MXHEL),CTVEC(NCOOR,MXHEL), &
       CVEC(NCOOR,MXSLT,MXHEL),CU(9,MXHEL), &
       CEV(3,MXHEL),CSVAL(2),CPVEC(NCOOR,MXSLT-2,MXHEL), &
       HDIST(MXCONSH),DFOR(MXCONSH),ANGL(MXCONSH),AFOR(MXCONSH)

  INTEGER CCOUNT,MCOUNT,TCOUNT,RCOUNT,PCOUNT,XCOUNT,HBCOUNT
  INTEGER NSEL(MXHEL,MXCONSH),CHNUM,OCHNUM, &
       CHUNIT(MXCONSH),CHSTEP(MXCONSH), &
       CHUNITA(MXCONSH),CHSTEPA(MXCONSH), &
       REFA(MXCONSH)

  type(chm_iptr), save :: ASLCT(MXCONSH), BSLCT(MXCONSH)
  INTEGER, allocatable :: SSLCT(:,:),JJSLCT(:,:)

  Logical LLDNA,LLBHG,LLBHP
  Logical LHMODC,LDNAM,LBHPM,LBHGM
  !   Logical LRAXM,LRAYM,LRAZM
  Logical QCONSH,MIND,LPARL(MXCONSH),LLIMIT(MXCONSH), &
       XANG(MXCONSH),LOHEL(MXCONSH),LCOMM(MXCONSH), &
       LCROS(MXCONSH),LHING(MXCONSH),LHMOD(MXCONSH), &
       LPHII(MXCONSH), &
       LTAX(MXCONSH),LTAY(MXCONSH),LTAZ(MXCONSH), &
       LROTH(MXCONSH),LAZAXIS(MXCONSH),LHARM(MXCONSH), &
       LRAX(MXCONSH),LRAY(MXCONSH),LRAZ(MXCONSH), &
       LDNA(MXCONSH),LBHG(MXCONSH),LBHP(MXCONSH)

#endif /* (CONSHELIX_FCM)*/

END MODULE CONSHELIX_FCM


