#if KEY_DIMB==1
SUBROUTINE BNDCMP(IAT,DE,DDE,DELX,DELY,DELZ,R,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from BNDRY routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Boundary potential routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER IAT
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DE,DDE,DELX,DELY,DELZ,R
  real(chm_real) DD1(*)
  ! Local variables
  INTEGER II,IADD,INII

  ! Begin
  II=IAT
  CALL INDDD1(II,INBCMP,INII)

  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDE*DELX*DELX+DE*(1.0-DELX*DELX)/R
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDE*DELY*DELY+DE*(1.0-DELY*DELY)/R
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDE*DELZ*DELZ+DE*(1.0-DELZ*DELZ)/R
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDE*DELX*DELY-DE*DELX*DELY/R
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDE*DELX*DELZ-DE*DELX*DELZ/R
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDE*DELY*DELZ-DE*DELY*DELZ/R


  RETURN
END SUBROUTINE BNDCMP

!
SUBROUTINE EANCMP(I,J,K,DDXIXI,DDYIYI,DDZIZI,DDXJXJ,DDYJYJ, &
     DDZJZJ,DDXIXJ,DDYIYJ,DDZIZJ,DDXIYI,DDXIZI, &
     DDYIZI,DDXJYJ,DDXJZJ,DDYJZJ,DDXIYJ,DDYIXJ, &
     DDXIZJ,DDZIXJ,DDYIZJ,DDZIYJ,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from EANGLE routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Angle energy routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J,K
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DDXIXI,DDYIYI,DDZIZI,DDXJXJ,DDYJYJ
  real(chm_real) DDZJZJ,DDXIXJ,DDYIYJ,DDZIZJ,DDXIYI,DDXIZI
  real(chm_real) DDYIZI,DDXJYJ,DDXJZJ,DDYJZJ,DDXIYJ,DDYIXJ
  real(chm_real) DDXIZJ,DDZIXJ,DDYIZJ,DDZIYJ
  real(chm_real) DD1(*)
  ! Local variables
  INTEGER II,JJ,KK,IADD,INII,INIJ
  LOGICAL IJTEST,IKTEST,JKTEST

  ! Begin
  II=I
  JJ=J
  KK=K
  IJTEST=(J < I)
  IKTEST=(K < I)
  JKTEST=(K < J)

  IF (IKTEST) THEN
     CALL OFFDD1(KK,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDXIXJ
     ! IADD=IUPT(KK+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDYIYJ
     ! IADD=IUPT(KK+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDZIZJ
     ! IADD=IUPT(KK)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDYIXJ
     ! IADD=IUPT(KK+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDXIYJ
     ! IADD=IUPT(KK)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDZIXJ
     ! IADD=IUPT(KK+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDXIZJ
     ! IADD=IUPT(KK+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDZIYJ
     ! IADD=IUPT(KK+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDYIZJ
  ELSE
     CALL OFFDD1(II,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDXIXJ
     ! IADD=IUPT(II+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDYIYJ
     ! IADD=IUPT(II+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDZIZJ
     ! IADD=IUPT(II+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDYIXJ
     ! IADD=IUPT(II)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDXIYJ
     ! IADD=IUPT(II+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDZIXJ
     ! IADD=IUPT(II)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDXIZJ
     ! IADD=IUPT(II+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDZIYJ
     ! IADD=IUPT(II+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDYIZJ
  ENDIF
  !
  IF (IJTEST) THEN
     CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXIXI
     ! IADD=IUPT(JJ+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYIYI
     ! IADD=IUPT(JJ+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZIZI
     ! IADD=IUPT(JJ)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDYIXJ
     ! IADD=IUPT(JJ+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDXIYJ
     ! IADD=IUPT(JJ)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDZIXJ
     ! IADD=IUPT(JJ+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDXIZJ
     ! IADD=IUPT(JJ+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDZIYJ
     ! IADD=IUPT(JJ+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDYIZJ
  ELSE
     CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXIXI
     ! IADD=IUPT(II+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYIYI
     ! IADD=IUPT(II+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZIZI
     ! IADD=IUPT(II+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDYIXJ
     ! IADD=IUPT(II)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDXIYJ
     ! IADD=IUPT(II+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDZIXJ
     ! IADD=IUPT(II)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDXIZJ
     ! IADD=IUPT(II+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDZIYJ
     ! IADD=IUPT(II+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDYIZJ
  ENDIF

  IF (JKTEST) THEN
     CALL OFFDD1(KK,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXJXJ
     ! IADD=IUPT(KK+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYJYJ
     ! IADD=IUPT(KK+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZJZJ
     ! IADD=IUPT(KK)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDYIXJ
     ! IADD=IUPT(KK+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDXIYJ
     ! IADD=IUPT(KK)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDZIXJ
     ! IADD=IUPT(KK+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDXIZJ
     ! IADD=IUPT(KK+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDZIYJ
     ! IADD=IUPT(KK+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDYIZJ
  ELSE
     CALL OFFDD1(JJ,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXJXJ
     ! IADD=IUPT(JJ+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYJYJ
     ! IADD=IUPT(JJ+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZJZJ
     ! IADD=IUPT(JJ+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDYIXJ
     ! IADD=IUPT(JJ)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDXIYJ
     ! IADD=IUPT(JJ+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDZIXJ
     ! IADD=IUPT(JJ)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDXIZJ
     ! IADD=IUPT(JJ+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDZIYJ
     ! IADD=IUPT(JJ+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDYIZJ
  ENDIF
  !
  ! Diagonal terms
  !
  CALL INDDD1(II,INBCMP,INII)
  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXIXI
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYIYI
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZIZI
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXIYI
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXIZI
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYIZI

  CALL INDDD1(KK,INBCMP,INII)
  ! IADD=IUPT(KK)+KK
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXJXJ
  ! IADD=IUPT(KK+1)+KK+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYJYJ
  ! IADD=IUPT(KK+2)+KK+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZJZJ
  ! IADD=IUPT(KK)+KK+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXJYJ
  ! IADD=IUPT(KK)+KK+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXJZJ
  ! IADD=IUPT(KK+1)+KK+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYJZJ

  CALL INDDD1(JJ,INBCMP,INII)
  ! IADD=IUPT(JJ)+JJ
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXIXI+DDXJXJ+DDXIXJ+DDXIXJ
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYIYI+DDYJYJ+DDYIYJ+DDYIYJ
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZIZI+DDZJZJ+DDZIZJ+DDZIZJ
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXIYI+DDXJYJ+DDXIYJ+DDYIXJ
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXIZI+DDXJZJ+DDXIZJ+DDZIXJ
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYIZI+DDYJZJ+DDYIZJ+DDZIYJ

  RETURN
END SUBROUTINE EANCMP

!
SUBROUTINE EBNCMP(I,J,RX,RY,RZ,DF,DDF,DD1,INBCMP,JNBCMP,KBEXPN)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from EBOND routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Bond energy routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J,KBEXPN
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) RX,RY,RZ,DF,DDF,DD1(*)
  ! Local variables
  INTEGER II,JJ,IADD,INII,INIJ,INJJ
  real(chm_real) A

  ! Begin
  IF(KBEXPN  /=  2) THEN
     CALL WRNDIE(-3,'<EBNCMP> ','NO SECOND DERIV. FOR ' &
          //'ANHARMONIC BONDS')
  ENDIF

  IF (J < I) THEN
     II=J
     JJ=I
  ELSE
     II=I
     JJ=J
  ENDIF
  !
  ! Get the indices pointing into DD1.
  !
  CALL INDDD1(II,INBCMP,INII)
  CALL INDDD1(JJ,INBCMP,INJJ)
  CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)

  A=RX*RX*DDF+DF
  ! IADD=IUPT(II)+JJ
  IADD=INIJ+IJXXCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ)+JJ
  IADD=INJJ+JJXXCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RY*RY*DDF+DF
  ! IADD=IUPT(II+1)+JJ+1
  IADD=INIJ+IJYYCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INJJ+JJYYCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RZ*RZ*DDF+DF
  ! IADD=IUPT(II+2)+JJ+2
  IADD=INIJ+IJZZCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INJJ+JJZZCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RX*RY*DDF
  ! IADD=IUPT(II)+JJ+1
  IADD=INIJ+IJXYCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+1)+JJ
  IADD=INIJ+IJYXCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INJJ+JJXYCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RX*RZ*DDF
  ! IADD=IUPT(II)+JJ+2
  IADD=INIJ+IJXZCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+2)+JJ
  IADD=INIJ+IJZXCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INJJ+JJXZCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RY*RZ*DDF
  ! IADD=IUPT(II+1)+JJ+2
  IADD=INIJ+IJYZCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+2)+JJ+1
  IADD=INIJ+IJZYCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INJJ+JJYZCM
  DD1(IADD)=DD1(IADD)+A

  RETURN
END SUBROUTINE EBNCMP

!
SUBROUTINE ECNCMP(I,AX,AY,AZ,DF,DDF,XHSCALE,YHSCALE,ZHSCALE, &
     DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from ECNSTR routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Harmonic positional constraints routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) AX,AY,AZ,DF,DDF,XHSCALE,YHSCALE,ZHSCALE
  real(chm_real) DD1(*)
  ! Local variables
  INTEGER II,IADD,INII

  ! Begin
  II=I
  CALL INDDD1(II,INBCMP,INII)

  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+(AX*AX*DDF*XHSCALE+DF)*XHSCALE
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+(AY*AY*DDF*YHSCALE+DF)*YHSCALE
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+(AZ*AZ*DDF*ZHSCALE+DF)*ZHSCALE
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+AX*AY*DDF*XHSCALE*YHSCALE
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+AX*AZ*DDF*XHSCALE*ZHSCALE
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+AY*AZ*DDF*YHSCALE*ZHSCALE

  RETURN
END SUBROUTINE ECNCMP


!
SUBROUTINE EG1CMP(I,J,IS,IQ,JS,JQ,NI,NJ,DFI,DXIC,DYIC,DZIC, &
     DXI,DYI,DZI,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     21-Dec-1994 Herman van Vlijmen (adapted from EGROUP routine)
  !
  !     Group-based non-bonded energy.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use number
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J,IS,IQ,JS,JQ,NI,NJ
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DFI,DXIC,DYIC,DZIC,DXI,DYI,DZI,DD1(*)
  ! Local variables
  INTEGER IX,JX,IADD,II,JJ,INII,INIJ
  real(chm_real) DFJ,DXIT,DYIT,DZIT,DXJT,DYJT,DZJT

  ! Begin

  ! Calculate 2*dF*dS term

  DFJ=DFI/NJ
  DFI=DFI/NI
  DXIT=DXIC*DFI
  DYIT=DYIC*DFI
  DZIT=DZIC*DFI
  DXJT=DXIC*DFJ
  DYJT=DYIC*DFJ
  DZJT=DZIC*DFJ

  DO IX=IS,IQ

     II=I
     JJ=IX

     IF (II == JJ) THEN
        CALL INDDD1(II,INBCMP,INII)
        ! IADD=IUPT(II)+II
        IADD=INII+IIXXCM
        DD1(IADD)=DD1(IADD)+DXI*DXIT*TWO
        ! IADD=IUPT(II+1)+II+1
        IADD=INII+IIYYCM
        DD1(IADD)=DD1(IADD)+DYI*DYIT*TWO
        ! IADD=IUPT(II+2)+II+2
        IADD=INII+IIZZCM
        DD1(IADD)=DD1(IADD)+DZI*DZIT*TWO
        ! IADD=IUPT(II)+II+1
        IADD=INII+IIXYCM
        DD1(IADD)=DD1(IADD)+DXI*DYIT+DYI*DXIT
        ! IADD=IUPT(II)+II+2
        IADD=INII+IIXZCM
        DD1(IADD)=DD1(IADD)+DXI*DZIT+DZI*DXIT
        ! IADD=IUPT(II+1)+II+2
        IADD=INII+IIYZCM
        DD1(IADD)=DD1(IADD)+DYI*DZIT+DZI*DYIT

     ELSE IF (JJ < II) THEN

        CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(JJ)+II
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)+DXI*DXIT
        ! IADD=IUPT(JJ+1)+II+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)+DYI*DYIT
        ! IADD=IUPT(JJ+2)+II+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)+DZI*DZIT
        ! IADD=IUPT(JJ)+II+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)+DYI*DXIT
        ! IADD=IUPT(JJ+1)+II
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)+DXI*DYIT
        ! IADD=IUPT(JJ)+II+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)+DZI*DXIT
        ! IADD=IUPT(JJ+2)+II
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)+DXI*DZIT
        ! IADD=IUPT(JJ+1)+II+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)+DZI*DYIT
        ! IADD=IUPT(JJ+2)+II+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)+DYI*DZIT

     ELSE

        CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(II)+JJ
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)+DXI*DXIT
        ! IADD=IUPT(II+1)+JJ+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)+DYI*DYIT
        ! IADD=IUPT(II+2)+JJ+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)+DZI*DZIT
        ! IADD=IUPT(II+1)+JJ
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)+DYI*DXIT
        ! IADD=IUPT(II)+JJ+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)+DXI*DYIT
        ! IADD=IUPT(II+2)+JJ
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)+DZI*DXIT
        ! IADD=IUPT(II)+JJ+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)+DXI*DZIT
        ! IADD=IUPT(II+2)+JJ+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)+DZI*DYIT
        ! IADD=IUPT(II+1)+JJ+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)+DYI*DZIT

     ENDIF

     II=J
     JJ=IX

     IF (JJ < II) THEN

        CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(JJ)+II
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)-DXI*DXIT
        ! IADD=IUPT(JJ+1)+II+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)-DYI*DYIT
        ! IADD=IUPT(JJ+2)+II+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)-DZI*DZIT
        ! IADD=IUPT(JJ)+II+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)-DYI*DXIT
        ! IADD=IUPT(JJ+1)+II
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)-DXI*DYIT
        ! IADD=IUPT(JJ)+II+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)-DZI*DXIT
        ! IADD=IUPT(JJ+2)+II
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)-DXI*DZIT
        ! IADD=IUPT(JJ+1)+II+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)-DZI*DYIT
        ! IADD=IUPT(JJ+2)+II+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)-DYI*DZIT

     ELSE

        CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(II)+JJ
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)-DXI*DXIT
        ! IADD=IUPT(II+1)+JJ+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)-DYI*DYIT
        ! IADD=IUPT(II+2)+JJ+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)-DZI*DZIT
        ! IADD=IUPT(II+1)+JJ
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)-DYI*DXIT
        ! IADD=IUPT(II)+JJ+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)-DXI*DYIT
        ! IADD=IUPT(II+2)+JJ
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)-DZI*DXIT
        ! IADD=IUPT(II)+JJ+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)-DXI*DZIT
        ! IADD=IUPT(II+2)+JJ+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)-DZI*DYIT
        ! IADD=IUPT(II+1)+JJ+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)-DYI*DZIT

     ENDIF
  ENDDO  ! DO IX=IS,IQ

  DO JX=JS,JQ

     II=I
     JJ=JX

     IF (JJ < II) THEN

        CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(JJ)+II
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)-DXI*DXJT
        ! IADD=IUPT(JJ+1)+II+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)-DYI*DYJT
        ! IADD=IUPT(JJ+2)+II+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)-DZI*DZJT
        ! IADD=IUPT(JJ)+II+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)-DYI*DXJT
        ! IADD=IUPT(JJ+1)+II
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)-DXI*DYJT
        ! IADD=IUPT(JJ)+II+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)-DZI*DXJT
        ! IADD=IUPT(JJ+2)+II
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)-DXI*DZJT
        ! IADD=IUPT(JJ+1)+II+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)-DZI*DYJT
        ! IADD=IUPT(JJ+2)+II+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)-DYI*DZJT

     ELSE

        CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(II)+JJ
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)-DXI*DXJT
        ! IADD=IUPT(II+1)+JJ+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)-DYI*DYJT
        ! IADD=IUPT(II+2)+JJ+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)-DZI*DZJT
        ! IADD=IUPT(II+1)+JJ
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)-DYI*DXJT
        ! IADD=IUPT(II)+JJ+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)-DXI*DYJT
        ! IADD=IUPT(II+2)+JJ
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)-DZI*DXJT
        ! IADD=IUPT(II)+JJ+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)-DXI*DZJT
        ! IADD=IUPT(II+2)+JJ+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)-DZI*DYJT
        ! IADD=IUPT(II+1)+JJ+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)-DYI*DZJT

     ENDIF

     II=J
     JJ=JX

     IF (II == JJ) THEN

        CALL INDDD1(II,INBCMP,INII)
        ! IADD=IUPT(II)+II
        IADD=INII+IIXXCM
        DD1(IADD)=DD1(IADD)+DXI*DXJT*TWO
        ! IADD=IUPT(II+1)+II+1
        IADD=INII+IIYYCM
        DD1(IADD)=DD1(IADD)+DYI*DYJT*TWO
        ! IADD=IUPT(II+2)+II+2
        IADD=INII+IIZZCM
        DD1(IADD)=DD1(IADD)+DZI*DZJT*TWO
        ! IADD=IUPT(II)+II+1
        IADD=INII+IIXYCM
        DD1(IADD)=DD1(IADD)+DXI*DYJT+DYI*DXJT
        ! IADD=IUPT(II)+II+2
        IADD=INII+IIXZCM
        DD1(IADD)=DD1(IADD)+DXI*DZJT+DZI*DXJT
        ! IADD=IUPT(II+1)+II+2
        IADD=INII+IIYZCM
        DD1(IADD)=DD1(IADD)+DYI*DZJT+DZI*DYJT

     ELSE IF (JJ < II) THEN

        CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(JJ)+II
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)+DXI*DXJT
        ! IADD=IUPT(JJ+1)+II+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)+DYI*DYJT
        ! IADD=IUPT(JJ+2)+II+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)+DZI*DZJT
        ! IADD=IUPT(JJ)+II+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)+DYI*DXJT
        ! IADD=IUPT(JJ+1)+II
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)+DXI*DYJT
        ! IADD=IUPT(JJ)+II+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)+DZI*DXJT
        ! IADD=IUPT(JJ+2)+II
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)+DXI*DZJT
        ! IADD=IUPT(JJ+1)+II+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)+DZI*DYJT
        ! IADD=IUPT(JJ+2)+II+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)+DYI*DZJT

     ELSE

        CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
        ! IADD=IUPT(II)+JJ
        IADD=INIJ+IJXXCM
        DD1(IADD)=DD1(IADD)+DXI*DXJT
        ! IADD=IUPT(II+1)+JJ+1
        IADD=INIJ+IJYYCM
        DD1(IADD)=DD1(IADD)+DYI*DYJT
        ! IADD=IUPT(II+2)+JJ+2
        IADD=INIJ+IJZZCM
        DD1(IADD)=DD1(IADD)+DZI*DZJT
        ! IADD=IUPT(II+1)+JJ
        IADD=INIJ+IJYXCM
        DD1(IADD)=DD1(IADD)+DYI*DXJT
        ! IADD=IUPT(II)+JJ+1
        IADD=INIJ+IJXYCM
        DD1(IADD)=DD1(IADD)+DXI*DYJT
        ! IADD=IUPT(II+2)+JJ
        IADD=INIJ+IJZXCM
        DD1(IADD)=DD1(IADD)+DZI*DXJT
        ! IADD=IUPT(II)+JJ+2
        IADD=INIJ+IJXZCM
        DD1(IADD)=DD1(IADD)+DXI*DZJT
        ! IADD=IUPT(II+2)+JJ+1
        IADD=INIJ+IJZYCM
        DD1(IADD)=DD1(IADD)+DZI*DYJT
        ! IADD=IUPT(II+1)+JJ+2
        IADD=INIJ+IJYZCM
        DD1(IADD)=DD1(IADD)+DYI*DZJT

     ENDIF
  ENDDO  ! DO JX=JS,JQ

  RETURN
END SUBROUTINE EG1CMP

!
SUBROUTINE EG2CMP(IS,IQ,JS,JQ,NI,NJ,DFN,DDFN,ETEMP1,ETEMP2, &
     DXIC,DYIC,DZIC,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     21-Dec-1994 Herman van Vlijmen (adapted from EGROUP routine)
  !
  !     Group-based non-bonded energy.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER IS,IQ,JS,JQ,NI,NJ
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DFN,DDFN,DXIC,DYIC,DZIC,DD1(*),ETEMP1,ETEMP2
  ! Local variables
  INTEGER I,J,IX,JX,IADD,II,JJ,INII,INIJ
  real(chm_real) DDF,DFI,DFJ

  ! Begin

  ! Calculate F*d2S term

  DDF=DDFN*(ETEMP1+ETEMP2)
  DFI=DDF/(NI*NI)
  DFJ=DFN/(NI*NI)

  DO I=IS,IQ
     DO IX=I,IQ

        II=3*I-2
        JJ=3*IX-2
        IF (II == JJ) THEN

           CALL INDDD1(II,INBCMP,INII)
           ! IADD=IUPT(II)+II
           IADD=INII+IIXXCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DXIC+DFJ
           ! IADD=IUPT(II+1)+II+1
           IADD=INII+IIYYCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DYIC+DFJ
           ! IADD=IUPT(II+2)+II+2
           IADD=INII+IIZZCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DZIC+DFJ
           ! IADD=IUPT(II)+II+1
           IADD=INII+IIXYCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DYIC
           ! IADD=IUPT(II)+II+2
           IADD=INII+IIXZCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DZIC
           ! IADD=IUPT(II+1)+II+2
           IADD=INII+IIYZCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DZIC

        ELSE

           CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
           ! IADD=IUPT(II)+JJ
           IADD=INIJ+IJXXCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DXIC+DFJ
           ! IADD=IUPT(II+1)+JJ+1
           IADD=INIJ+IJYYCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DYIC+DFJ
           ! IADD=IUPT(II+2)+JJ+2
           IADD=INIJ+IJZZCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DZIC+DFJ
           ! IADD=IUPT(II+1)+JJ
           IADD=INIJ+IJYXCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DXIC
           ! IADD=IUPT(II)+JJ+1
           IADD=INIJ+IJXYCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DYIC
           ! IADD=IUPT(II+2)+JJ
           IADD=INIJ+IJZXCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DXIC
           ! IADD=IUPT(II)+JJ+2
           IADD=INIJ+IJXZCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DZIC
           ! IADD=IUPT(II+2)+JJ+1
           IADD=INIJ+IJZYCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DYIC
           ! IADD=IUPT(II+1)+JJ+2
           IADD=INIJ+IJYZCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DZIC

        ENDIF
     ENDDO  ! IX=I,IQ
  ENDDO     ! I=IS,IQ

  DFI=DDF/(NJ*NJ)
  DFJ=DFN/(NJ*NJ)

  DO J=JS,JQ
     DO JX=J,JQ

        II=J
        JJ=JX
        IF (II == JJ) THEN

           CALL INDDD1(II,INBCMP,INII)
           ! IADD=IUPT(II)+II
           IADD=INII+IIXXCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DXIC+DFJ
           ! IADD=IUPT(II+1)+II+1
           IADD=INII+IIYYCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DYIC+DFJ
           ! IADD=IUPT(II+2)+II+2
           IADD=INII+IIZZCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DZIC+DFJ
           ! IADD=IUPT(II)+II+1
           IADD=INII+IIXYCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DYIC
           ! IADD=IUPT(II)+II+2
           IADD=INII+IIXZCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DZIC
           ! IADD=IUPT(II+1)+II+2
           IADD=INII+IIYZCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DZIC

        ELSE

           CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
           ! IADD=IUPT(II)+JJ
           IADD=INIJ+IJXXCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DXIC+DFJ
           ! IADD=IUPT(II+1)+JJ+1
           IADD=INIJ+IJYYCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DYIC+DFJ
           ! IADD=IUPT(II+2)+JJ+2
           IADD=INIJ+IJZZCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DZIC+DFJ
           ! IADD=IUPT(II+1)+JJ
           IADD=INIJ+IJYXCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DXIC
           ! IADD=IUPT(II)+JJ+1
           IADD=INIJ+IJXYCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DYIC
           ! IADD=IUPT(II+2)+JJ
           IADD=INIJ+IJZXCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DXIC
           ! IADD=IUPT(II)+JJ+2
           IADD=INIJ+IJXZCM
           DD1(IADD)=DD1(IADD)+DFI*DXIC*DZIC
           ! IADD=IUPT(II+2)+JJ+1
           IADD=INIJ+IJZYCM
           DD1(IADD)=DD1(IADD)+DFI*DZIC*DYIC
           ! IADD=IUPT(II+1)+JJ+2
           IADD=INIJ+IJYZCM
           DD1(IADD)=DD1(IADD)+DFI*DYIC*DZIC

        ENDIF
     ENDDO  ! JX=J,JQ
  ENDDO     ! J=JS,JQ

  DFI=DDF/(NI*NJ)
  DFJ=DFN/(NI*NJ)

  DO I=IS,IQ
     DO J=JS,JQ
        II=I
        JJ=J
        IF(JJ < II) THEN

           CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
           ! IADD=IUPT(JJ)+II
           IADD=INIJ+IJXXCM
           DD1(IADD)=DD1(IADD)-DFI*DXIC*DXIC-DFJ
           ! IADD=IUPT(JJ+1)+II+1
           IADD=INIJ+IJYYCM
           DD1(IADD)=DD1(IADD)-DFI*DYIC*DYIC-DFJ
           ! IADD=IUPT(JJ+2)+II+2
           IADD=INIJ+IJZZCM
           DD1(IADD)=DD1(IADD)-DFI*DZIC*DZIC-DFJ
           ! IADD=IUPT(JJ)+II+1
           IADD=INIJ+IJXYCM
           DD1(IADD)=DD1(IADD)-DFI*DYIC*DXIC
           ! IADD=IUPT(JJ+1)+II
           IADD=INIJ+IJYXCM
           DD1(IADD)=DD1(IADD)-DFI*DXIC*DYIC
           ! IADD=IUPT(JJ)+II+2
           IADD=INIJ+IJXZCM
           DD1(IADD)=DD1(IADD)-DFI*DZIC*DXIC
           ! IADD=IUPT(JJ+2)+II
           IADD=INIJ+IJZXCM
           DD1(IADD)=DD1(IADD)-DFI*DXIC*DZIC
           ! IADD=IUPT(JJ+1)+II+2
           IADD=INIJ+IJYZCM
           DD1(IADD)=DD1(IADD)-DFI*DZIC*DYIC
           ! IADD=IUPT(JJ+2)+II+1
           IADD=INIJ+IJZYCM
           DD1(IADD)=DD1(IADD)-DFI*DYIC*DZIC

        ELSE

           CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
           ! IADD=IUPT(II)+JJ
           IADD=INIJ+IJXXCM
           DD1(IADD)=DD1(IADD)-DFI*DXIC*DXIC-DFJ
           ! IADD=IUPT(II+1)+JJ+1
           IADD=INIJ+IJYYCM
           DD1(IADD)=DD1(IADD)-DFI*DYIC*DYIC-DFJ
           ! IADD=IUPT(II+2)+JJ+2
           IADD=INIJ+IJZZCM
           DD1(IADD)=DD1(IADD)-DFI*DZIC*DZIC-DFJ
           ! IADD=IUPT(II+1)+JJ
           IADD=INIJ+IJYXCM
           DD1(IADD)=DD1(IADD)-DFI*DYIC*DXIC
           ! IADD=IUPT(II)+JJ+1
           IADD=INIJ+IJXYCM
           DD1(IADD)=DD1(IADD)-DFI*DXIC*DYIC
           ! IADD=IUPT(II+2)+JJ
           IADD=INIJ+IJZXCM
           DD1(IADD)=DD1(IADD)-DFI*DZIC*DXIC
           ! IADD=IUPT(II)+JJ+2
           IADD=INIJ+IJXZCM
           DD1(IADD)=DD1(IADD)-DFI*DXIC*DZIC
           ! IADD=IUPT(II+2)+JJ+1
           IADD=INIJ+IJZYCM
           DD1(IADD)=DD1(IADD)-DFI*DZIC*DYIC
           ! IADD=IUPT(II+1)+JJ+2
           IADD=INIJ+IJYZCM
           DD1(IADD)=DD1(IADD)-DFI*DYIC*DZIC

        ENDIF
     ENDDO  ! J=JS,JQ
  ENDDO     ! I=IS,IQ

  RETURN
END SUBROUTINE EG2CMP


!
SUBROUTINE EHBCMP(II,JJ,KK,LL,DDRXX,DDRYY,DDRZZ,DDRXY,DDRXZ,DDRYZ, &
     DDXIXI,DDYIYI,DDZIZI,DDXIYI,DDXIZI,DDYIZI, &
     DDXIXR,DDYIYR,DDZIZR,DDXIYR,DDXIZR,DDYIXR,DDYIZR,DDZIXR,DDZIYR, &
     DDXJXJ,DDYJYJ,DDZJZJ,DDXJYJ,DDXJZJ,DDYJZJ, &
     DDXJXR,DDYJYR,DDZJZR,DDXJYR,DDXJZR,DDYJXR,DDYJZR,DDZJXR,DDZJYR, &
     DDXLXL,DDYLYL,DDZLZL,DDXLYL,DDXLZL,DDYLZL, &
     DDXLXR,DDYLYR,DDZLZR,DDXLYR,DDXLZR,DDYLXR,DDYLZR,DDZLXR,DDZLYR, &
     DDXLXJ,DDYLYJ,DDZLZJ,DDXLYJ,DDXLZJ,DDYLXJ,DDYLZJ,DDZLXJ,DDZLYJ, &
     DDXIXJ,DDYIYJ,DDZIZJ,DDXIYJ,DDXIZJ,DDYIXJ,DDYIZJ,DDZIXJ,DDZIYJ, &
     DDXIXL,DDYIYL,DDZIZL,DDXIYL,DDXIZL,DDYIXL,DDYIZL,DDZIXL,DDZIYL, &
     DD1,INBCMP,JNBCMP)
  !---------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from EHBOND routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Hydrogen bond energy routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !---------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER II,JJ,KK,LL
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DDRXX,DDRYY,DDRZZ,DDRXY,DDRXZ,DDRYZ
  real(chm_real) DDXIXI,DDYIYI,DDZIZI,DDXIYI,DDXIZI,DDYIZI
  real(chm_real) DDXIXR,DDYIYR,DDZIZR,DDXIYR,DDXIZR,DDYIXR
  real(chm_real) DDYIZR,DDZIXR,DDZIYR
  real(chm_real) DDXJXJ,DDYJYJ,DDZJZJ,DDXJYJ,DDXJZJ,DDYJZJ
  real(chm_real) DDXJXR,DDYJYR,DDZJZR,DDXJYR,DDXJZR,DDYJXR
  real(chm_real) DDYJZR,DDZJXR,DDZJYR
  real(chm_real) DDXLXL,DDYLYL,DDZLZL,DDXLYL,DDXLZL,DDYLZL
  real(chm_real) DDXLXR,DDYLYR,DDZLZR,DDXLYR,DDXLZR,DDYLXR
  real(chm_real) DDYLZR,DDZLXR,DDZLYR
  real(chm_real) DDXLXJ,DDYLYJ,DDZLZJ,DDXLYJ,DDXLZJ,DDYLXJ
  real(chm_real) DDYLZJ,DDZLXJ,DDZLYJ
  real(chm_real) DDXIXJ,DDYIYJ,DDZIZJ,DDXIYJ,DDXIZJ,DDYIXJ
  real(chm_real) DDYIZJ,DDZIXJ,DDZIYJ
  real(chm_real) DDXIXL,DDYIYL,DDZIZL,DDXIYL,DDXIZL,DDYIXL
  real(chm_real) DDYIZL,DDZIXL,DDZIYL
  real(chm_real) DD1(*)
  ! Local variables
  INTEGER IADD,INII,INIJ,INJJ
  LOGICAL IJTEST,IKTEST,JKTEST,ILTEST,JLTEST,KLTEST

  ! Begin
  IJTEST=(JJ < II)
  IKTEST=(KK < II)
  JKTEST=(KK < JJ)
  ILTEST=(LL < II)
  JLTEST=(LL < JJ)
  KLTEST=(LL < KK)

  !
  ! Diagonal elements
  !
  CALL INDDD1(II,INBCMP,INII)
  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXIXI+DDRXX+DDXIXR+DDXIXR
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYIYI+DDRYY+DDYIYR+DDYIYR
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZIZI+DDRZZ+DDZIZR+DDZIZR
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXIYI+DDRXY+DDXIYR+DDYIXR
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXIZI+DDRXZ+DDXIZR+DDZIXR
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYIZI+DDRYZ+DDYIZR+DDZIYR
  !
  CALL INDDD1(JJ,INBCMP,INII)
  ! IADD=IUPT(JJ)+JJ
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXJXJ+DDRXX-DDXJXR-DDXJXR &
       -DDXLXR-DDXLXR+DDXLXL+DDXLXJ+DDXLXJ
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYJYJ+DDRYY-DDYJYR-DDYJYR &
       -DDYLYR-DDYLYR+DDYLYL+DDYLYJ+DDYLYJ
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZJZJ+DDRZZ-DDZJZR-DDZJZR &
       -DDZLZR-DDZLZR+DDZLZL+DDZLZJ+DDZLZJ
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXJYJ+DDRXY-DDXJYR-DDYJXR &
       -DDXLYR-DDYLXR+DDXLYL+DDXLYJ+DDYLXJ
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXJZJ+DDRXZ-DDXJZR-DDZJXR &
       -DDXLZR-DDZLXR+DDXLZL+DDXLZJ+DDZLXJ
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYJZJ+DDRYZ-DDYJZR-DDZJYR &
       -DDYLZR-DDZLYR+DDYLZL+DDYLZJ+DDZLYJ
  !
  CALL INDDD1(KK,INBCMP,INII)
  ! IADD=IUPT(KK)+KK
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXIXI+DDXJXJ+DDXIXJ+DDXIXJ
  ! IADD=IUPT(KK+1)+KK+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYIYI+DDYJYJ+DDYIYJ+DDYIYJ
  ! IADD=IUPT(KK+2)+KK+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZIZI+DDZJZJ+DDZIZJ+DDZIZJ
  ! IADD=IUPT(KK)+KK+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXIYI+DDXJYJ+DDXIYJ+DDYIXJ
  ! IADD=IUPT(KK)+KK+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXIZI+DDXJZJ+DDXIZJ+DDZIXJ
  ! IADD=IUPT(KK+1)+KK+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYIZI+DDYJZJ+DDYIZJ+DDZIYJ
  !
  CALL INDDD1(LL,INBCMP,INII)
  ! IADD=IUPT(LL)+LL
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDXLXL
  ! IADD=IUPT(LL+1)+LL+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDYLYL
  ! IADD=IUPT(LL+2)+LL+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDZLZL
  ! IADD=IUPT(LL)+LL+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDXLYL
  ! IADD=IUPT(LL)+LL+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDXLZL
  ! IADD=IUPT(LL+1)+LL+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDYLZL
  !
  ! Off diagonal terms
  !
  IF(IJTEST) THEN
     CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDXIXJ-DDRXX-DDXIXR+DDXJXR+DDXIXL+DDXLXR
     ! IADD=IUPT(JJ+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDYIYJ-DDRYY-DDYIYR+DDYJYR+DDYIYL+DDYLYR
     ! IADD=IUPT(JJ+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDZIZJ-DDRZZ-DDZIZR+DDZJZR+DDZIZL+DDZLZR
     ! IADD=IUPT(JJ)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDYIXJ-DDRXY+DDXJYR-DDYIXR+DDYIXL+DDXLYR
     ! IADD=IUPT(JJ+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDXIYJ-DDRXY+DDYJXR-DDXIYR+DDXIYL+DDYLXR
     ! IADD=IUPT(JJ)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDZIXJ-DDRXZ+DDXJZR-DDZIXR+DDZIXL+DDXLZR
     ! IADD=IUPT(JJ+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDXIZJ-DDRXZ+DDZJXR-DDXIZR+DDXIZL+DDZLXR
     ! IADD=IUPT(JJ+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDZIYJ-DDRYZ+DDYJZR-DDZIYR+DDZIYL+DDYLZR
     ! IADD=IUPT(JJ+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDYIZJ-DDRYZ+DDZJYR-DDYIZR+DDYIZL+DDZLYR
  ELSE
     CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDXIXJ-DDRXX-DDXIXR+DDXJXR+DDXIXL+DDXLXR
     ! IADD=IUPT(II+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDYIYJ-DDRYY-DDYIYR+DDYJYR+DDYIYL+DDYLYR
     ! IADD=IUPT(II+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDZIZJ-DDRZZ-DDZIZR+DDZJZR+DDZIZL+DDZLZR
     ! IADD=IUPT(II+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDYIXJ-DDRXY+DDXJYR-DDYIXR+DDYIXL+DDXLYR
     ! IADD=IUPT(II)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDXIYJ-DDRXY+DDYJXR-DDXIYR+DDXIYL+DDYLXR
     ! IADD=IUPT(II+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDZIXJ-DDRXZ+DDXJZR-DDZIXR+DDZIXL+DDXLZR
     ! IADD=IUPT(II)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDXIZJ-DDRXZ+DDZJXR-DDXIZR+DDXIZL+DDZLXR
     ! IADD=IUPT(II+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDZIYJ-DDRYZ+DDYJZR-DDZIYR+DDZIYL+DDYLZR
     ! IADD=IUPT(II+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDYIZJ-DDRYZ+DDZJYR-DDYIZR+DDYIZL+DDZLYR
  ENDIF
  !
  IF(IKTEST) THEN
     CALL OFFDD1(KK,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXIXI-DDXIXR-DDXJXR
     ! IADD=IUPT(KK+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYIYI-DDYIYR-DDYJYR
     ! IADD=IUPT(KK+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZIZI-DDZIZR-DDZJZR
     ! IADD=IUPT(KK)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDYIXJ-DDXJYR-DDXIYR
     ! IADD=IUPT(KK+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDXIYJ-DDYJXR-DDYIXR
     ! IADD=IUPT(KK)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDZIXJ-DDXJZR-DDXIZR
     ! IADD=IUPT(KK+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDXIZJ-DDZJXR-DDZIXR
     ! IADD=IUPT(KK+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDZIYJ-DDYJZR-DDYIZR
     ! IADD=IUPT(KK+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDYIZJ-DDZJYR-DDZIYR
  ELSE
     CALL OFFDD1(II,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXIXI-DDXIXR-DDXJXR
     ! IADD=IUPT(II+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYIYI-DDYIYR-DDYJYR
     ! IADD=IUPT(II+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZIZI-DDZIZR-DDZJZR
     ! IADD=IUPT(II+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDYIXJ-DDXJYR-DDXIYR
     ! IADD=IUPT(II)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXIYI-DDXIYJ-DDYJXR-DDYIXR
     ! IADD=IUPT(II+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDZIXJ-DDXJZR-DDXIZR
     ! IADD=IUPT(II)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXIZI-DDXIZJ-DDZJXR-DDZIXR
     ! IADD=IUPT(II+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDZIYJ-DDYJZR-DDYIZR
     ! IADD=IUPT(II+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYIZI-DDYIZJ-DDZJYR-DDZIYR
  ENDIF

  IF(JKTEST) THEN
     CALL OFFDD1(KK,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXJXJ+DDXIXR+DDXJXR-DDXIXL-DDXLXJ
     ! IADD=IUPT(KK+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYJYJ+DDYIYR+DDYJYR-DDYIYL-DDYLYJ
     ! IADD=IUPT(KK+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZJZJ+DDZIZR+DDZJZR-DDZIZL-DDZLZJ
     ! IADD=IUPT(KK)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDXIYJ+DDXJYR+DDXIYR-DDXIYL-DDYLXJ
     ! IADD=IUPT(KK+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDYIXJ+DDYJXR+DDYIXR-DDYIXL-DDXLYJ
     ! IADD=IUPT(KK)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDXIZJ+DDXJZR+DDXIZR-DDXIZL-DDZLXJ
     ! IADD=IUPT(KK+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDZIXJ+DDZJXR+DDZIXR-DDZIXL-DDXLZJ
     ! IADD=IUPT(KK+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDYIZJ+DDYJZR+DDYIZR-DDYIZL-DDZLYJ
     ! IADD=IUPT(KK+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDZIYJ+DDZJYR+DDZIYR-DDZIYL-DDYLZJ
  ELSE
     CALL OFFDD1(JJ,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXJ-DDXJXJ+DDXIXR+DDXJXR-DDXIXL-DDXLXJ
     ! IADD=IUPT(JJ+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYJ-DDYJYJ+DDYIYR+DDYJYR-DDYIYL-DDYLYJ
     ! IADD=IUPT(JJ+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZJ-DDZJZJ+DDZIZR+DDZJZR-DDZIZL-DDZLZJ
     ! IADD=IUPT(JJ+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDXIYJ+DDXJYR+DDXIYR-DDXIYL-DDYLXJ
     ! IADD=IUPT(JJ)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXJYJ-DDYIXJ+DDYJXR+DDYIXR-DDYIXL-DDXLYJ
     ! IADD=IUPT(JJ+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDXIZJ+DDXJZR+DDXIZR-DDXIZL-DDZLXJ
     ! IADD=IUPT(JJ)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXJZJ-DDZIXJ+DDZJXR+DDZIXR-DDZIXL-DDXLZJ
     ! IADD=IUPT(JJ+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDYIZJ+DDYJZR+DDYIZR-DDYIZL-DDZLYJ
     ! IADD=IUPT(JJ+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYJZJ-DDZIYJ+DDZJYR+DDZIYR-DDZIYL-DDYLZJ
  ENDIF

  IF(JLTEST) THEN
     CALL OFFDD1(LL,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(LL)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXLXJ+DDXLXR-DDXLXL
     ! IADD=IUPT(LL+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYLYJ+DDYLYR-DDYLYL
     ! IADD=IUPT(LL+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZLZJ+DDZLZR-DDZLZL
     ! IADD=IUPT(LL)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXLYJ+DDXLYR-DDXLYL
     ! IADD=IUPT(LL+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDYLXJ+DDYLXR-DDXLYL
     ! IADD=IUPT(LL)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXLZJ+DDXLZR-DDXLZL
     ! IADD=IUPT(LL+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDZLXJ+DDZLXR-DDXLZL
     ! IADD=IUPT(LL+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYLZJ+DDYLZR-DDYLZL
     ! IADD=IUPT(LL+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDZLYJ+DDZLYR-DDYLZL
  ELSE
     CALL OFFDD1(JJ,LL,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+LL
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXLXJ+DDXLXR-DDXLXL
     ! IADD=IUPT(JJ+1)+LL+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYLYJ+DDYLYR-DDYLYL
     ! IADD=IUPT(JJ+2)+LL+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZLZJ+DDZLZR-DDZLZL
     ! IADD=IUPT(JJ+1)+LL
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXLYJ+DDXLYR-DDXLYL
     ! IADD=IUPT(JJ)+LL+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDYLXJ+DDYLXR-DDXLYL
     ! IADD=IUPT(JJ+2)+LL
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXLZJ+DDXLZR-DDXLZL
     ! IADD=IUPT(JJ)+LL+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDZLXJ+DDZLXR-DDXLZL
     ! IADD=IUPT(JJ+2)+LL+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYLZJ+DDYLZR-DDYLZL
     ! IADD=IUPT(JJ+1)+LL+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDZLYJ+DDZLYR-DDYLZL
  ENDIF

  IF(KLTEST) THEN
     CALL OFFDD1(LL,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(LL)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDXIXL+DDXLXJ
     ! IADD=IUPT(LL+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDYIYL+DDYLYJ
     ! IADD=IUPT(LL+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDZIZL+DDZLZJ
     ! IADD=IUPT(LL)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDYIXL+DDXLYJ
     ! IADD=IUPT(LL+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDXIYL+DDYLXJ
     ! IADD=IUPT(LL)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDZIXL+DDXLZJ
     ! IADD=IUPT(LL+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDXIZL+DDZLXJ
     ! IADD=IUPT(LL+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDZIYL+DDYLZJ
     ! IADD=IUPT(LL+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDYIZL+DDZLYJ
  ELSE
     CALL OFFDD1(KK,LL,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+LL
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDXIXL+DDXLXJ
     ! IADD=IUPT(KK+1)+LL+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDYIYL+DDYLYJ
     ! IADD=IUPT(KK+2)+LL+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDZIZL+DDZLZJ
     ! IADD=IUPT(KK+1)+LL
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDYIXL+DDXLYJ
     ! IADD=IUPT(KK)+LL+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDXIYL+DDYLXJ
     ! IADD=IUPT(KK+2)+LL
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDZIXL+DDXLZJ
     ! IADD=IUPT(KK)+LL+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDXIZL+DDZLXJ
     ! IADD=IUPT(KK+2)+LL+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDZIYL+DDYLZJ
     ! IADD=IUPT(KK+1)+LL+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDYIZL+DDZLYJ
  ENDIF
  !
  IF(ILTEST) THEN
     CALL OFFDD1(LL,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(LL)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXL-DDXLXR
     ! IADD=IUPT(LL+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYL-DDYLYR
     ! IADD=IUPT(LL+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZL-DDZLZR
     ! IADD=IUPT(LL)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDYIXL-DDXLYR
     ! IADD=IUPT(LL+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDXIYL-DDYLXR
     ! IADD=IUPT(LL)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDZIXL-DDXLZR
     ! IADD=IUPT(LL+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDXIZL-DDZLXR
     ! IADD=IUPT(LL+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDZIYL-DDYLZR
     ! IADD=IUPT(LL+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDYIZL-DDZLYR
  ELSE
     CALL OFFDD1(II,LL,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+LL
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDXIXL-DDXLXR
     ! IADD=IUPT(II+1)+LL+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDYIYL-DDYLYR
     ! IADD=IUPT(II+2)+LL+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDZIZL-DDZLZR
     ! IADD=IUPT(II+1)+LL
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDYIXL-DDXLYR
     ! IADD=IUPT(II)+LL+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDXIYL-DDYLXR
     ! IADD=IUPT(II+2)+LL
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDZIXL-DDXLZR
     ! IADD=IUPT(II)+LL+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDXIZL-DDZLXR
     ! IADD=IUPT(II+2)+LL+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDZIYL-DDYLZR
     ! IADD=IUPT(II+1)+LL+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDYIZL-DDZLYR
  ENDIF

  RETURN
END SUBROUTINE EHBCMP

!
SUBROUTINE EPHCMP(I,J,K,L,DDFGH,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from EPHI routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Dihedral and improper dihedral energy routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J,K,L
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DDFGH(45),DD1(*)
  ! Local variables
  INTEGER II,JJ,KK,LL,IADD,INII,INIJ,INJJ
  LOGICAL IJTEST,IKTEST,JKTEST,ILTEST,JLTEST,KLTEST

  ! Begin
  II=I
  JJ=J
  KK=K
  LL=L
  IJTEST=(J < I)
  IKTEST=(K < I)
  JKTEST=(K < J)
  ILTEST=(L < I)
  JLTEST=(L < J)
  KLTEST=(L < K)

  CALL INDDD1(II,INBCMP,INII)
  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDFGH(1)
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDFGH(3)
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDFGH(6)
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDFGH(2)
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDFGH(4)
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDFGH(5)
  !
  CALL INDDD1(LL,INBCMP,INII)
  ! IADD=IUPT(LL)+LL
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDFGH(28)
  ! IADD=IUPT(LL+1)+LL+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDFGH(36)
  ! IADD=IUPT(LL+2)+LL+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDFGH(45)
  ! IADD=IUPT(LL)+LL+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDFGH(35)
  ! IADD=IUPT(LL)+LL+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDFGH(43)
  ! IADD=IUPT(LL+1)+LL+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDFGH(44)
  !
  CALL INDDD1(JJ,INBCMP,INII)
  ! IADD=IUPT(JJ)+JJ
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDFGH(1)+DDFGH(10)-DDFGH(7)-DDFGH(7)
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDFGH(3)+DDFGH(15)-DDFGH(12)-DDFGH(12)
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDFGH(6)+DDFGH(21)-DDFGH(18)-DDFGH(18)
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDFGH(2)+DDFGH(14)-DDFGH(11)-DDFGH(8)
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDFGH(4)+DDFGH(19)-DDFGH(16)-DDFGH(9)
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDFGH(5)+DDFGH(20)-DDFGH(17)-DDFGH(13)
  !
  CALL INDDD1(KK,INBCMP,INII)
  ! IADD=IUPT(KK)+KK
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+DDFGH(28)+DDFGH(10)+DDFGH(25)+DDFGH(25)
  ! IADD=IUPT(KK+1)+KK+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+DDFGH(36)+DDFGH(15)+DDFGH(33)+DDFGH(33)
  ! IADD=IUPT(KK+2)+KK+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+DDFGH(45)+DDFGH(21)+DDFGH(42)+DDFGH(42)
  ! IADD=IUPT(KK)+KK+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+DDFGH(35)+DDFGH(14)+DDFGH(32)+DDFGH(26)
  ! IADD=IUPT(KK)+KK+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+DDFGH(43)+DDFGH(19)+DDFGH(40)+DDFGH(27)
  ! IADD=IUPT(KK+1)+KK+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+DDFGH(44)+DDFGH(20)+DDFGH(41)+DDFGH(34)
  !
  IF (IJTEST) THEN
     CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(7)-DDFGH(1)
     ! IADD=IUPT(JJ+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(12)-DDFGH(3)
     ! IADD=IUPT(JJ+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(18)-DDFGH(6)
     ! IADD=IUPT(JJ)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(8)-DDFGH(2)
     ! IADD=IUPT(JJ+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(11)-DDFGH(2)
     ! IADD=IUPT(JJ)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(9)-DDFGH(4)
     ! IADD=IUPT(JJ+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(16)-DDFGH(4)
     ! IADD=IUPT(JJ+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(13)-DDFGH(5)
     ! IADD=IUPT(JJ+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(17)-DDFGH(5)
  ELSE
     CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(7)-DDFGH(1)
     ! IADD=IUPT(II+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(12)-DDFGH(3)
     ! IADD=IUPT(II+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(18)-DDFGH(6)
     ! IADD=IUPT(II+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(8)-DDFGH(2)
     ! IADD=IUPT(II)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(11)-DDFGH(2)
     ! IADD=IUPT(II+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(9)-DDFGH(4)
     ! IADD=IUPT(II)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(16)-DDFGH(4)
     ! IADD=IUPT(II+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(13)-DDFGH(5)
     ! IADD=IUPT(II+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(17)-DDFGH(5)
  ENDIF
  !
  IF (IKTEST) THEN
     CALL OFFDD1(KK,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDFGH(7)-DDFGH(22)
     ! IADD=IUPT(KK+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDFGH(12)-DDFGH(30)
     ! IADD=IUPT(KK+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDFGH(18)-DDFGH(39)
     ! IADD=IUPT(KK)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDFGH(8)-DDFGH(23)
     ! IADD=IUPT(KK+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDFGH(11)-DDFGH(29)
     ! IADD=IUPT(KK)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDFGH(9)-DDFGH(24)
     ! IADD=IUPT(KK+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDFGH(16)-DDFGH(37)
     ! IADD=IUPT(KK+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDFGH(13)-DDFGH(31)
     ! IADD=IUPT(KK+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDFGH(17)-DDFGH(38)
  ELSE
     CALL OFFDD1(II,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDFGH(7)-DDFGH(22)
     ! IADD=IUPT(II+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDFGH(12)-DDFGH(30)
     ! IADD=IUPT(II+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDFGH(18)-DDFGH(39)
     ! IADD=IUPT(II+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDFGH(8)-DDFGH(23)
     ! IADD=IUPT(II)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDFGH(11)-DDFGH(29)
     ! IADD=IUPT(II+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDFGH(9)-DDFGH(24)
     ! IADD=IUPT(II)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDFGH(16)-DDFGH(37)
     ! IADD=IUPT(II+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDFGH(13)-DDFGH(31)
     ! IADD=IUPT(II+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDFGH(17)-DDFGH(38)
  ENDIF
  !
  IF (ILTEST) THEN
     CALL OFFDD1(LL,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(LL)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(22)
     ! IADD=IUPT(LL+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(30)
     ! IADD=IUPT(LL+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(39)
     ! IADD=IUPT(LL)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(23)
     ! IADD=IUPT(LL+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(29)
     ! IADD=IUPT(LL)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(24)
     ! IADD=IUPT(LL+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(37)
     ! IADD=IUPT(LL+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(31)
     ! IADD=IUPT(LL+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(38)
  ELSE
     CALL OFFDD1(II,LL,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+LL
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(22)
     ! IADD=IUPT(II+1)+LL+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(30)
     ! IADD=IUPT(II+2)+LL+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(39)
     ! IADD=IUPT(II+1)+LL
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(23)
     ! IADD=IUPT(II)+LL+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(29)
     ! IADD=IUPT(II+2)+LL
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(24)
     ! IADD=IUPT(II)+LL+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(37)
     ! IADD=IUPT(II+2)+LL+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(31)
     ! IADD=IUPT(II+1)+LL+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(38)
  ENDIF
  !
  IF (JKTEST) THEN
     CALL OFFDD1(KK,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(7)+DDFGH(22)-DDFGH(10)-DDFGH(25)
     ! IADD=IUPT(KK+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(12)+DDFGH(30)-DDFGH(15)-DDFGH(33)
     ! IADD=IUPT(KK+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(18)+DDFGH(39)-DDFGH(21)-DDFGH(42)
     ! IADD=IUPT(KK)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(8)+DDFGH(23)-DDFGH(14)-DDFGH(26)
     ! IADD=IUPT(KK+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(11)+DDFGH(29)-DDFGH(14)-DDFGH(32)
     ! IADD=IUPT(KK)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(9)+DDFGH(24)-DDFGH(19)-DDFGH(27)
     ! IADD=IUPT(KK+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(16)+DDFGH(37)-DDFGH(19)-DDFGH(40)
     ! IADD=IUPT(KK+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(13)+DDFGH(31)-DDFGH(20)-DDFGH(34)
     ! IADD=IUPT(KK+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(17)+DDFGH(38)-DDFGH(20)-DDFGH(41)
  ELSE
     CALL OFFDD1(JJ,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(7)+DDFGH(22)-DDFGH(10)-DDFGH(25)
     ! IADD=IUPT(JJ+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(12)+DDFGH(30)-DDFGH(15)-DDFGH(33)
     ! IADD=IUPT(JJ+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(18)+DDFGH(39)-DDFGH(21)-DDFGH(42)
     ! IADD=IUPT(JJ+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(8)+DDFGH(23)-DDFGH(14)-DDFGH(26)
     ! IADD=IUPT(JJ)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(11)+DDFGH(29)-DDFGH(14)-DDFGH(32)
     ! IADD=IUPT(JJ+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(9)+DDFGH(24)-DDFGH(19)-DDFGH(27)
     ! IADD=IUPT(JJ)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(16)+DDFGH(37)-DDFGH(19)-DDFGH(40)
     ! IADD=IUPT(JJ+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(13)+DDFGH(31)-DDFGH(20)-DDFGH(34)
     ! IADD=IUPT(JJ+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(17)+DDFGH(38)-DDFGH(20)-DDFGH(41)
  ENDIF
  !
  IF (JLTEST) THEN
     CALL OFFDD1(LL,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(LL)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(25)-DDFGH(22)
     ! IADD=IUPT(LL+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(33)-DDFGH(30)
     ! IADD=IUPT(LL+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(42)-DDFGH(39)
     ! IADD=IUPT(LL)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(26)-DDFGH(23)
     ! IADD=IUPT(LL+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(32)-DDFGH(29)
     ! IADD=IUPT(LL)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(27)-DDFGH(24)
     ! IADD=IUPT(LL+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(40)-DDFGH(37)
     ! IADD=IUPT(LL+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(34)-DDFGH(31)
     ! IADD=IUPT(LL+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(41)-DDFGH(38)
  ELSE
     CALL OFFDD1(JJ,LL,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+LL
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)+DDFGH(25)-DDFGH(22)
     ! IADD=IUPT(JJ+1)+LL+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)+DDFGH(33)-DDFGH(30)
     ! IADD=IUPT(JJ+2)+LL+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)+DDFGH(42)-DDFGH(39)
     ! IADD=IUPT(JJ+1)+LL
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)+DDFGH(26)-DDFGH(23)
     ! IADD=IUPT(JJ)+LL+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)+DDFGH(32)-DDFGH(29)
     ! IADD=IUPT(JJ+2)+LL
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)+DDFGH(27)-DDFGH(24)
     ! IADD=IUPT(JJ)+LL+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)+DDFGH(40)-DDFGH(37)
     ! IADD=IUPT(JJ+2)+LL+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)+DDFGH(34)-DDFGH(31)
     ! IADD=IUPT(JJ+1)+LL+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)+DDFGH(41)-DDFGH(38)
  ENDIF
  !
  IF (KLTEST) THEN
     CALL OFFDD1(LL,KK,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(LL)+KK
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDFGH(25)-DDFGH(28)
     ! IADD=IUPT(LL+1)+KK+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDFGH(33)-DDFGH(36)
     ! IADD=IUPT(LL+2)+KK+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDFGH(42)-DDFGH(45)
     ! IADD=IUPT(LL)+KK+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDFGH(26)-DDFGH(35)
     ! IADD=IUPT(LL+1)+KK
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDFGH(32)-DDFGH(35)
     ! IADD=IUPT(LL)+KK+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDFGH(27)-DDFGH(43)
     ! IADD=IUPT(LL+2)+KK
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDFGH(40)-DDFGH(43)
     ! IADD=IUPT(LL+1)+KK+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDFGH(34)-DDFGH(44)
     ! IADD=IUPT(LL+2)+KK+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDFGH(41)-DDFGH(44)
  ELSE
     CALL OFFDD1(KK,LL,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(KK)+LL
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-DDFGH(25)-DDFGH(28)
     ! IADD=IUPT(KK+1)+LL+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-DDFGH(33)-DDFGH(36)
     ! IADD=IUPT(KK+2)+LL+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-DDFGH(42)-DDFGH(45)
     ! IADD=IUPT(KK+1)+LL
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-DDFGH(26)-DDFGH(35)
     ! IADD=IUPT(KK)+LL+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-DDFGH(32)-DDFGH(35)
     ! IADD=IUPT(KK+2)+LL
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-DDFGH(27)-DDFGH(43)
     ! IADD=IUPT(KK)+LL+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-DDFGH(40)-DDFGH(43)
     ! IADD=IUPT(KK+2)+LL+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-DDFGH(34)-DDFGH(44)
     ! IADD=IUPT(KK+1)+LL+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-DDFGH(41)-DDFGH(44)
  ENDIF

  RETURN
END SUBROUTINE EPHCMP

!
SUBROUTINE ETACMP(I,J,AXX,AXY,AXZ,AYY,AYZ,AZZ,DD1,INBCMP,JNBCMP)
  !---------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from ETABLE routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Table lookup nonbonded energy routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !---------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) AXX,AXY,AXZ,AYY,AYZ,AZZ
  real(chm_real) DD1(*)
  ! Local variables
  INTEGER II,JJ,IADD,INII,INIJ,INJJ
  LOGICAL IJTEST

  ! Begin
  II=I
  JJ=J
  IJTEST=(J < I)
  !
  ! Get pointers into DD1
  !
  CALL INDDD1(II,INBCMP,INII)

  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+AXX
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+AYY
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+AZZ
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+AXY
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+AXZ
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+AYZ

  INJJ=(JJ-1)*6+INBCMP(JJ-1)*9
  ! IADD=IUPT(JJ)+JJ
  IADD=INJJ+JJXXCM
  DD1(IADD)=DD1(IADD)+AXX
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INJJ+JJYYCM
  DD1(IADD)=DD1(IADD)+AYY
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INJJ+JJZZCM
  DD1(IADD)=DD1(IADD)+AZZ
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INJJ+JJXYCM
  DD1(IADD)=DD1(IADD)+AXY
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INJJ+JJXZCM
  DD1(IADD)=DD1(IADD)+AXZ
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INJJ+JJYZCM
  DD1(IADD)=DD1(IADD)+AYZ

  IF(IJTEST) THEN
     CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-AXX
     ! IADD=IUPT(JJ+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-AYY
     ! IADD=IUPT(JJ+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-AZZ
     ! IADD=IUPT(JJ)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(JJ+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(JJ)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(JJ+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(JJ+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-AYZ
     ! IADD=IUPT(JJ+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-AYZ
  ELSE
     CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-AXX
     ! IADD=IUPT(II+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-AYY
     ! IADD=IUPT(II+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-AZZ
     ! IADD=IUPT(II+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(II)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(II+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(II)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(II+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-AYZ
     ! IADD=IUPT(II+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-AYZ
  ENDIF

  RETURN
END SUBROUTINE ETACMP

!
SUBROUTINE EVDCMP(I,J,AXX,AYY,AZZ,AXY,AXZ,AYZ,DD1,INBCMP,JNBCMP)
  !---------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from EVDW routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     VDW and electrostatic energy routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are
  !     commented out.
  !---------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) AXX,AYY,AZZ,AXY,AXZ,AYZ
  real(chm_real) DD1(*)
  ! Local variables
  INTEGER II,JJ,IADD,INII,INIJ,INJJ
  LOGICAL IJTEST

  ! Begin
  II=I
  JJ=J
  IJTEST=(J < I)

  CALL INDDD1(II,INBCMP,INII)
  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+AXX
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+AYY
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+AZZ
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+AXY
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+AXZ
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+AYZ

  CALL INDDD1(JJ,INBCMP,INII)
  ! IADD=IUPT(JJ)+JJ
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+AXX
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+AYY
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+AZZ
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+AXY
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+AXZ
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+AYZ

  IF (IJTEST) THEN
     CALL OFFDD1(JJ,II,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(JJ)+II
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-AXX
     ! IADD=IUPT(JJ+1)+II+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-AYY
     ! IADD=IUPT(JJ+2)+II+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-AZZ
     ! IADD=IUPT(JJ)+II+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(JJ+1)+II
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(JJ)+II+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(JJ+2)+II
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(JJ+1)+II+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-AYZ
     ! IADD=IUPT(JJ+2)+II+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-AYZ
  ELSE
     CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)
     ! IADD=IUPT(II)+JJ
     IADD=INIJ+IJXXCM
     DD1(IADD)=DD1(IADD)-AXX
     ! IADD=IUPT(II+1)+JJ+1
     IADD=INIJ+IJYYCM
     DD1(IADD)=DD1(IADD)-AYY
     ! IADD=IUPT(II+2)+JJ+2
     IADD=INIJ+IJZZCM
     DD1(IADD)=DD1(IADD)-AZZ
     ! IADD=IUPT(II+1)+JJ
     IADD=INIJ+IJYXCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(II)+JJ+1
     IADD=INIJ+IJXYCM
     DD1(IADD)=DD1(IADD)-AXY
     ! IADD=IUPT(II+2)+JJ
     IADD=INIJ+IJZXCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(II)+JJ+2
     IADD=INIJ+IJXZCM
     DD1(IADD)=DD1(IADD)-AXZ
     ! IADD=IUPT(II+2)+JJ+1
     IADD=INIJ+IJZYCM
     DD1(IADD)=DD1(IADD)-AYZ
     ! IADD=IUPT(II+1)+JJ+2
     IADD=INIJ+IJYZCM
     DD1(IADD)=DD1(IADD)-AYZ
  ENDIF

  RETURN
END SUBROUTINE EVDCMP

!
SUBROUTINE NOECMP(I,J,RX,RY,RZ,DF,DDF,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from NOECNS routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     NOE constraints routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  use dimb
  implicit none
  ! Passed variables
  INTEGER I,J
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) RX,RY,RZ,DF,DDF,DD1(*)
  ! Local variables
  INTEGER II,JJ,IADD,INII,INIJ,INJJ
  real(chm_real) A

  ! Begin
  IF(J < I) THEN
     JJ=I
     II=J
  ELSE
     JJ=J
     II=I
  ENDIF
  !
  ! Get pointers into DD1
  !
  CALL INDDD1(II,INBCMP,INII)
  CALL INDDD1(JJ,INBCMP,INJJ)
  CALL OFFDD1(II,JJ,INBCMP,JNBCMP,INIJ)

  A=RX*RX*DDF+DF
  ! IADD=IUPT(II)+JJ
  IADD=INIJ+IJXXCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II)+II
  IADD=INII+IIXXCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ)+JJ
  IADD=INJJ+JJXXCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RY*RY*DDF+DF
  ! IADD=IUPT(II+1)+JJ+1
  IADD=INIJ+IJYYCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+1)+II+1
  IADD=INII+IIYYCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ+1)+JJ+1
  IADD=INJJ+JJYYCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RZ*RZ*DDF+DF
  ! IADD=IUPT(II+2)+JJ+2
  IADD=INIJ+IJZZCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+2)+II+2
  IADD=INII+IIZZCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ+2)+JJ+2
  IADD=INJJ+JJZZCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RX*RY*DDF
  ! IADD=IUPT(II)+JJ+1
  IADD=INIJ+IJXYCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+1)+JJ
  IADD=INIJ+IJYXCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II)+II+1
  IADD=INII+IIXYCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ)+JJ+1
  IADD=INJJ+JJXYCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RX*RZ*DDF
  ! IADD=IUPT(II)+JJ+2
  IADD=INIJ+IJXZCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+2)+JJ
  IADD=INIJ+IJZXCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II)+II+2
  IADD=INII+IIXZCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ)+JJ+2
  IADD=INJJ+JJXZCM
  DD1(IADD)=DD1(IADD)+A
  !
  A=RY*RZ*DDF
  ! IADD=IUPT(II+1)+JJ+2
  IADD=INIJ+IJYZCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+2)+JJ+1
  IADD=INIJ+IJZYCM
  DD1(IADD)=DD1(IADD)-A
  ! IADD=IUPT(II+1)+II+2
  IADD=INII+IIYZCM
  DD1(IADD)=DD1(IADD)+A
  ! IADD=IUPT(JJ+1)+JJ+2
  IADD=INJJ+JJYZCM
  DD1(IADD)=DD1(IADD)+A
  RETURN
END SUBROUTINE NOECMP
#else /**/

SUBROUTINE BNDCMP(IAT,DE,DDE,DELX,DELY,DELZ,R,DD1,INBCMP,JNBCMP)
  !--------------------------------------------------------------------
  !     01-Jul-1992 David Perahia (adapted from BNDRY routine)
  !     08-Dec-1994 Herman van Vlijmen
  !
  !     Boundary potential routine.
  !     Calculate second derivatives for compressed Hessian matrix
  !     The original command lines from the energy routines are 
  !     commented out.
  !--------------------------------------------------------------------
  use chm_kinds
  implicit none
  ! Passed variables
  INTEGER IAT
  INTEGER INBCMP(*),JNBCMP(*)
  real(chm_real) DE,DDE,DELX,DELY,DELZ,R
  real(chm_real) DD1(*)
  return
end SUBROUTINE BNDCMP
#endif /*  DIMB*/

