#! /bin/csh -x

cp $1 $1.origlogs
sed "s/\.[Gg][Tt]\./\ >\ /" $1.origlogs | \
sed "s/\.[Gg][Ee]\./\ >=\ /"  | \
sed "s/\.[Ll][Tt]\./\ <\ /"  | \
sed "s/\.[Ll][Ee]\./\ <=\ /" | \
sed "s/\.[Ee][Qq]\./\ ==\ /" | \
sed "s?\.[Nn][Ee]\.?\ /=\ ?"  >! $1
