list(APPEND sccdftb_fortran_files
  source/sccdftbint/sccdftbini.F90
  source/sccdftbint/sccpme.F90
  source/sccdftbint/sccpmeutil.F90
  source/sccdftbint/stbgho.F90
  source/sccdftbint/stbgho_ltm.F90
  source/sccdftbint/sccdftbsrc/cpe.F90
  source/sccdftbint/sccdftbsrc/dftd3.F90
  source/sccdftbint/sccdftbsrc/diis.F90
  source/sccdftbint/sccdftbsrc/atomen.f
  source/sccdftbint/sccdftbsrc/broyden.f
  source/sccdftbint/sccdftbsrc/dispersion_egr.f
  source/sccdftbint/sccdftbsrc/dispersionread.f
  source/sccdftbint/sccdftbsrc/dxlc.f
  source/sccdftbint/sccdftbsrc/externalshift.f
  source/sccdftbint/sccdftbsrc/fermi.f
  source/sccdftbint/sccdftbsrc/gamma.f
  source/sccdftbint/sccdftbsrc/gammamat.f
  source/sccdftbint/sccdftbsrc/geometries.f
  source/sccdftbint/sccdftbsrc/gettab.f
  source/sccdftbint/sccdftbsrc/inicof.f
  source/sccdftbint/sccdftbsrc/long_range.f
  source/sccdftbint/sccdftbsrc/output.f
  source/sccdftbint/sccdftbsrc/repulsiv.f
  source/sccdftbint/sccdftbsrc/self.f
  source/sccdftbint/sccdftbsrc/shift.f
  source/sccdftbint/sccdftbsrc/short_range.f
  source/sccdftbint/sccdftbsrc/skpar.f
  source/sccdftbint/sccdftbsrc/slkode.f
  source/sccdftbint/sccdftbsrc/slktrafo.f
  source/sccdftbint/sccdftbsrc/dylcao.F
  source/sccdftbint/sccdftbsrc/eglcao.F
  source/sccdftbint/sccdftbsrc/externalchgrad.F
  source/sccdftbint/sccdftbsrc/ktable_ewscc.F
  source/sccdftbint/sccdftbsrc/long_sccmm1.F
  source/sccdftbint/sccdftbsrc/long_sccmm2.F
  source/sccdftbint/sccdftbsrc/long_sccpme.F
  source/sccdftbint/sccdftbsrc/mixer.F
  source/sccdftbint/sccdftbsrc/ewevge.F
  source/sccdftbint/sccdftbsrc/gradient.F
  source/sccdftbint/sccdftbsrc/mulliken.F)
